# Generated by Django 4.2.14 on 2024-07-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad1', '0002_line_productname_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('material_warehouse_manager', 'Начальник склада материалов'), ('finished_goods_warehouse_manager', 'Начальник склада готовой продукции'), ('sales_director', 'Директор по продажам')], max_length=40),
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Line',
        ),
        migrations.DeleteModel(
            name='ProductName',
        ),
    ]
